### ISSUE TITLE
Update Shib to work correctly with oxAuth 3.1.0

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxShibboleth#28]
Initial issue was:
```
Can't proceed with CAS testing, seems like Shib integration doesn't work:

Problem accessing /idp/Authn/RemoteUser. Reason:

    Server Error
Caused by:

java.lang.NoSuchMethodError: org.jboss.resteasy.client.ClientResponse.getLocationLink()Lorg/jboss/resteasy/spi/Link;
 at org.xdi.oxauth.client.BaseResponse.<init>(BaseResponse.java:36)
 at org.xdi.oxauth.client.BaseResponseWithErrors.<init>(BaseResponseWithErrors.java:33)
 at org.xdi.oxauth.client.TokenResponse.<init>(TokenResponse.java:42)
 at org.xdi.oxauth.client.TokenClient.exec(TokenClient.java:280)
 at org.xdi.oxauth.client.TokenClient.execAuthorizationCode(TokenClient.java:84)
```

**Comment by yurem** [comment]
After fixing it in this [commit](https://github.com/GluuFederation/oxShibboleth/commit/051d616c93552b57dbee3a5997b2e89491417a97) we get another issue:
```
Now it's not even reaching RemoteUser redirection stage
2017-08-02 19:31:23,058 - ERROR [org.springframework.beans.factory.CannotLoadBeanClassException:76] - 
org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [net.shibboleth.idp.cas.flow.impl.ValidateIdpSessionAction] for bean with name 'ValidateIdPSession' defined in file [/opt/shibboleth-idp/system/flows/cas/login/../cas-abstract-beans.xml]; nested exception is java.lang.ClassNotFoundException: net.shibboleth.idp.cas.flow.impl.ValidateIdpSessionAction
 at
```

This shows that [update to Shib 3.3.1](https://github.com/GluuFederation/oxShibboleth/commit/fae65eb3f749856a42ed0a728491f1c7eaffd141) which we did few days ago requires also beans xml update.

In Shib 3.3.1 source codes there is net.shibboleth.idp.cas.flow.impl.ValidateIdpSessionAction class

**Comment by dmogn** [comment]
Done
